[project]
name = "leetcode_grind"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pytest>8"]

[tool.setuptools.packages.find]
where = ["python"]
exclude = ["rust", "target"]

[tool.pytest.ini_options]
python_files = ["*.py"]
